apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${issuer_name}
spec:
  acme:
    server: ${server}
    email: ${acme_email}
    privateKeySecretRef:
      name: ${issuer_name}-key
    solvers:
      %{ if solver_type == "HTTP01" }
      - http01:
          ingress:
            class: nginx
      %{ endif }
      %{ if solver_type == "DNS01_CLOUDFLARE" }
      - dns01:
          cloudflare:
            email: ${cloudflare_email}
            apiKeySecretRef:
              name: ${dns_secret_name}
              key: api-key
      %{ endif }
      %{ if solver_type == "DNS01_HETZNER" }
      - dns01:
          webhook:
            solverName: hetzner
            groupName: ${groupName}
            config:
              secretName: ${dns_secret_name}
              zoneName: ${zoneName}
              apiUrl: ${hetzner_api_url}
      %{ endif }